# You are given application log lines generated by a backend API service.
# Write a function that extracts all HTTP status codes and returns their occurrence count.

logs = [
"2026-05-19 10:00:21 INFO service=checkout status=200 latency=45ms",
"2026-05-19 10:00:24 ERROR service=payments status=500 latency=1200ms",
"2026-05-19 10:00:30 WARN service=auth status=401 latency=90ms",
"2026-05-19 10:00:40 ERROR service=checkout status=503 latency=2000ms"
]


def count_status_codes(logs):
    counts = {}
    
    for log in logs:
        parts = log.split()

        for part in parts:
            if part.startswith("status="):
                status = part.split("=")[1]

                if status in counts:
                    counts[status] += 1
                else:
                    counts[status] = 1
    return counts


print(count_status_codes(logs))


